### ISSUE TITLE
échec sur la version web

### ISSUE THREAD

**Issue by mgageo** [nlehuby/gtfs_geo#1]
J'ai le message suivant
Ooops, somethins went wrong, sorry!
sur le traitement du fichier
https://data.explore.star.fr/api/v2/catalog/datasets/tco-busmetro-horaires-gtfs-versions-td/files/2512ee306c7f95004bb112052b56c632

**Comment by nlehuby** [comment]
Merci pour ce retour.

Hum, je pense que le fichier est un peu trop gros pour ce cas d'usage : sur mon poste, il m'a fallu 12 minutes pour le traiter :thinking:

**Comment by mgageo** [comment]
Ma VM est un peu plus performante
[```
root@debian10:~/gtfs_geo/gtfs_geo# time python3 cli.py star.zip
>>> launching

real    3m12,646s
user    3m11,854s
sys     0m0,516s
root@debian10:~/gtfs_geo/gtfs_geo#]
```
il faudrait peut-être tester la taille du fichier après téléchargement et signaler qu'il est trop gros.
