### ISSUE TITLE
Convertion sans succès

### ISSUE THREAD

**Issue by Futur3r** [nlehuby/gtfs_geo#3]
J'ai essayer d'utiliser GTFS > Geo sur ce jeu de données : https://transport.data.gouv.fr/datasets/offre-de-transports-sibra-a-annecy-gtfs .

Avec ce lien : https://static.data.gouv.fr/resources/offre-de-transports-sibra-a-annecy-gtfs/20200821-090711/gtfs-sibra-jybus-202009.zip .

Mais sans succès, est ce que les données sont mal formatés ?

**Comment by nlehuby** [comment]
Bonjour,

en effet, la version de démo sur heroku ne permet de gérer que des petits fichiers GTFS, désolée pour cette limitation.

Voici le résultat sur ce GTFS : https://drop.chapril.org/download/da56160f094044ba/#zzWJhpYho-6GVmGTSEBvNA

**Comment by Futur3r** [comment]
Ok, merci pour les données !
